/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Report = IDL.Record({
  'summary' : IDL.Text,
  'generatedAtNs' : IDL.Int,
});
export const Pattern = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'mfeMaeRatio' : IDL.Float64,
  'plainEnglishSentence' : IDL.Text,
  'coverage' : IDL.Float64,
  'winRate' : IDL.Float64,
});
export const DatasetRef = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const DiscoveryConfig = IDL.Record({
  'minMfeMaeRatio' : IDL.Float64,
  'horizon' : IDL.Nat,
  'mfeMaeWindow' : IDL.Nat,
  'mfeMaeRatioEnabled' : IDL.Bool,
  'minSampleSize' : IDL.Nat,
  'maxDepth' : IDL.Nat,
  'minWinRate' : IDL.Float64,
});
export const ValidationResult = IDL.Record({
  'outOfSampleWinRate' : IDL.Float64,
  'inSampleWinRate' : IDL.Float64,
  'byMarketCondition' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const SavedRun = IDL.Record({
  'id' : IDL.Nat,
  'report' : Report,
  'patterns' : IDL.Vec(Pattern),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'datasets' : IDL.Vec(DatasetRef),
  'savedAtNs' : IDL.Int,
  'config' : DiscoveryConfig,
  'validation' : ValidationResult,
});
export const SavedRunSummary = IDL.Record({
  'id' : IDL.Nat,
  'patternCount' : IDL.Nat,
  'name' : IDL.Text,
  'configSummary' : IDL.Text,
  'datasetName' : IDL.Text,
  'savedAtNs' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMyDefinitionRegistry' : IDL.Func([], [IDL.Bool], []),
  'deleteMyRun' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyDefinitionRegistry' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyRun' : IDL.Func([IDL.Nat], [IDL.Opt(SavedRun)], []),
  'getMyRuns' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(SavedRun)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyRunSummaries' : IDL.Func([], [IDL.Vec(SavedRunSummary)], []),
  'listMyRuns' : IDL.Func([], [IDL.Vec(SavedRun)], []),
  'saveMyDefinitionRegistry' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveRun' : IDL.Func([SavedRun], [SavedRun], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Report = IDL.Record({
    'summary' : IDL.Text,
    'generatedAtNs' : IDL.Int,
  });
  const Pattern = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'mfeMaeRatio' : IDL.Float64,
    'plainEnglishSentence' : IDL.Text,
    'coverage' : IDL.Float64,
    'winRate' : IDL.Float64,
  });
  const DatasetRef = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const DiscoveryConfig = IDL.Record({
    'minMfeMaeRatio' : IDL.Float64,
    'horizon' : IDL.Nat,
    'mfeMaeWindow' : IDL.Nat,
    'mfeMaeRatioEnabled' : IDL.Bool,
    'minSampleSize' : IDL.Nat,
    'maxDepth' : IDL.Nat,
    'minWinRate' : IDL.Float64,
  });
  const ValidationResult = IDL.Record({
    'outOfSampleWinRate' : IDL.Float64,
    'inSampleWinRate' : IDL.Float64,
    'byMarketCondition' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const SavedRun = IDL.Record({
    'id' : IDL.Nat,
    'report' : Report,
    'patterns' : IDL.Vec(Pattern),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'datasets' : IDL.Vec(DatasetRef),
    'savedAtNs' : IDL.Int,
    'config' : DiscoveryConfig,
    'validation' : ValidationResult,
  });
  const SavedRunSummary = IDL.Record({
    'id' : IDL.Nat,
    'patternCount' : IDL.Nat,
    'name' : IDL.Text,
    'configSummary' : IDL.Text,
    'datasetName' : IDL.Text,
    'savedAtNs' : IDL.Int,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMyDefinitionRegistry' : IDL.Func([], [IDL.Bool], []),
    'deleteMyRun' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyDefinitionRegistry' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyRun' : IDL.Func([IDL.Nat], [IDL.Opt(SavedRun)], []),
    'getMyRuns' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(SavedRun)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyRunSummaries' : IDL.Func([], [IDL.Vec(SavedRunSummary)], []),
    'listMyRuns' : IDL.Func([], [IDL.Vec(SavedRun)], []),
    'saveMyDefinitionRegistry' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveRun' : IDL.Func([SavedRun], [SavedRun], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
