/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface DatasetRef { 'id' : string, 'name' : string }
export interface DiscoveryConfig {
  'minMfeMaeRatio' : number,
  'horizon' : bigint,
  'mfeMaeWindow' : bigint,
  'mfeMaeRatioEnabled' : boolean,
  'minSampleSize' : bigint,
  'maxDepth' : bigint,
  'minWinRate' : number,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Pattern {
  'id' : string,
  'name' : string,
  'mfeMaeRatio' : number,
  'plainEnglishSentence' : string,
  'coverage' : number,
  'winRate' : number,
}
export interface Report { 'summary' : string, 'generatedAtNs' : bigint }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SavedRun {
  'id' : bigint,
  'report' : Report,
  'patterns' : Array<Pattern>,
  'owner' : Principal,
  'name' : string,
  'datasets' : Array<DatasetRef>,
  'savedAtNs' : bigint,
  'config' : DiscoveryConfig,
  'validation' : ValidationResult,
}
export interface SavedRunSummary {
  'id' : bigint,
  'patternCount' : bigint,
  'name' : string,
  'configSummary' : string,
  'datasetName' : string,
  'savedAtNs' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValidationResult {
  'outOfSampleWinRate' : number,
  'inSampleWinRate' : number,
  'byMarketCondition' : Array<[string, number]>,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMyRun' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRun' : ActorMethod<[bigint], [] | [SavedRun]>,
  'getMyRuns' : ActorMethod<[Array<bigint>], Array<SavedRun>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyRunSummaries' : ActorMethod<[], Array<SavedRunSummary>>,
  'listMyRuns' : ActorMethod<[], Array<SavedRun>>,
  'saveRun' : ActorMethod<[SavedRun], SavedRun>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];